### ISSUE TITLE
Build error while using Node 10

### ISSUE THREAD

**Issue by TanNgocDo** [confio/weave-js#14]
There is an error when I use node 10 to build project 
`In file included from ../node_modules/nan/nan.h:192:
../node_modules/nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);`

I switch back to node 9 and it works

**Comment by Isabello** [comment]
That looks like an issue in the dependecy, `nan`. You should report this to that repo. In the meantime, a note can be added that we only support node 8/9.

**Comment by TanNgocDo** [comment]
Thanks, it's already the issue of nan. The possible solution is use node 9.
